### ISSUE TITLE
Does not work in Python 3.7.3 with Pygame 1.9.5

### ISSUE THREAD

**Issue by chraibi** [godisreal/Many-Particle-System#5] opened 2019-04-04 18:38 UTC
After fixing some nasty errors related to mixed spaces and tabs,  I run 
```
python 3Particles/simulator_WP0817_3Particles.py
```
and see an empty windows
![Screenshot 2019-04-04 at 20 35 40](https://user-images.githubusercontent.com/5772973/55579783-56964b80-5719-11e9-821a-5867cb6ffd3f.png)

After clicking on the red x (close the window) a new window pops up

![Screenshot 2019-04-04 at 20 35 53](https://user-images.githubusercontent.com/5772973/55579791-5bf39600-5719-11e9-951b-1e7bd639e7a1.png)

Closing this one closes also the other one, and that's it. 

Am I supposed to see some circles moving around or not? 🤔

**Comment by godisreal** [comment] 2019-04-05 13:07
Thanks for your interest.  It seems that the source code is able to run on your computer, and there may be something wrong with pygame.  I do not know why the simulation screen is blank.  
Yes.  You are supposed to see three circles moving around.  The simulation was recorded in 3Particles.swf.  So do you run any other Python program with pygame?  So others are OK and only this one is blank on screen?  Please let me know whether you can debug it or not.  I compiled the code in Python 2.7 with Pygame 1.9.  Based on your description, it seems that pygame.draw.line() and pygame.draw.circle() does not output on the screen.  

Sorry for the error about tabs and spaces.  In fact the text edior confuses me a little.  I previously selected TABS and SPACES, and it caused an unexpected problem as you mentioned.  So I should only use SPACES and set TAB = 4 spaces.  Is that right?  Anyway, you are also welcome to give a pull request if you have already fixed this error.

**Comment by chraibi** [comment] 2019-04-06 19:23
I use pygame 1.9.5 and Python 3.7.3. 
I did not check other pygame-examples. Just wanted to see what this simulation is all about..
Yes, four spaces everywhere seem to be a good idea.

**Comment by godisreal** [comment] 2019-04-21 06:58
Please try the following program to test the pygame in Python 3.7.  If it does not work in your computer, it is probably a setup problem of pygrame with Python 3.7.  I am not sure.  Just try it.  There is no problem in computational model in the existing code.  Thank you for your question.

**Comment by godisreal** [comment] 2019-12-23 09:48
The problem may be related to pygame._view.  

When I use py2exe to get an execuable, the execuable file is successfully produced. 
However, when I run it, it returns the following error message.  I think the these problems are perhaps related issues.  

```

C:\Documents and Settings\WP\Desktop\PySim\Test_py2exe\dist>simulator_WP_Doorway
.exe
simulator_WP_Doorway.exe:4: RuntimeWarning: import display: No module named _view
(ImportError: No module named _view)
simulator_WP_Doorway.exe:4: RuntimeWarning: import draw: No module named _view
(ImportError: No module named _view)
simulator_WP_Doorway.exe:4: RuntimeWarning: import image: No module named _view
(ImportError: No module named _view)
simulator_WP_Doorway.exe:4: RuntimeWarning: import pixelcopy: No module named _view
(ImportError: No module named _view)
simulator_WP_Doorway.exe:4: RuntimeWarning: import transform: No module named _view
(ImportError: No module named _view)
Traceback (most recent call last):
  File "simulator_WP_Doorway.py", line 5, in <module>
  File "pygame\draw.pyc", line 12, in <module>
  File "pygame\draw.pyc", line 10, in __load
  File "pygame\surface.pyc", line 12, in <module>
  File "pygame\surface.pyc", line 10, in __load
ImportError: No module named _view
```

**Comment by godisreal** [comment] 2020-06-01 07:17
OK. So the developers of Pygame replied that the problem is related to OSX for mac users.  The details are listed as below.  
"Looking at the linked issue on the other github repo I'm almost certain this is just the standard 'modern OSX doesn't work with pygame 1/SDL1' issue we get reported every other week. Don't think there is any work for pygame here, other than telling people on mac to use pygame 2 whenever they ask, so I think I'll close this for now."  --- By  MyreMylar commented May 31, 2020

**Closed as completed** 2020-06-14 17:02 UTC
Labels: question
